### ISSUE TITLE
cannot start the motor due to AttributeError: type object 'Cursor' has no attribute 'allow_disk_use'

### ISSUE THREAD

**Issue by yuxx1006** [dcrosta/flask-pymongo#146]
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import motor.motor_asyncio
  File "/Users/xiao2/opt/anaconda3/envs/tf/lib/python3.7/site-packages/motor/__init__.py", line 35, in <module>
    from .motor_tornado import *
  File "/Users/xiao2/opt/anaconda3/envs/tf/lib/python3.7/site-packages/motor/motor_tornado.py", line 41, in <module>
    MotorCursor = create_motor_class(core.AgnosticCursor)
  File "/Users/xiao2/opt/anaconda3/envs/tf/lib/python3.7/site-packages/motor/motor_tornado.py", line 26, in create_motor_class
    'motor.motor_tornado')
  File "/Users/xiao2/opt/anaconda3/envs/tf/lib/python3.7/site-packages/motor/metaprogramming.py", line 288, in create_class_with_framework
    new_class_attr = attr.create_attribute(new_class, name)
  File "/Users/xiao2/opt/anaconda3/envs/tf/lib/python3.7/site-packages/motor/metaprogramming.py", line 251, in create_attribute
    cursor_method = getattr(cls.__delegate_class__, attr_name)
AttributeError: type object 'Cursor' has no attribute 'allow_disk_use'

**Comment by dcrosta** [comment]
https://github.com/mongodb/motor is a different project, please log this issue there. I also suggest you include versions of mongodb, pymongo, and steps to reproduce or some information about what you’re trying to do with it, it’s hard to diagnose a problem with only a stack trace.
