### ISSUE TITLE
Facing some issues regarding timeout

### ISSUE THREAD

**Issue by RampageousRJ** [dcrosta/flask-pymongo#168]
I have a deployed version of my code online which is running fine but when trying to run a local version of the same code, I am facing the errors
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\Study\OneDrive - Manipal Academy of Higher Education\Coding\Mini-Projects\Arihant-Ledger\virt\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "E:\Study\OneDrive - Manipal Academy of Higher Education\Coding\Mini-Projects\Arihant-Ledger\virt\Lib\site-packages\flask\cli.py", line 1105, in main
    cli.main()
  File "E:\Study\OneDrive - Manipal Academy of Higher Education\Coding\Mini-Projects\Arihant-Ledger\virt\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "E:\Study\OneDrive - Manipal Academy of Higher Education\Coding\Mini-Projects\Arihant-Ledger\virt\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Study\OneDrive - Manipal Academy of Higher Education\Coding\Mini-Projects\Arihant-Ledger\virt\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Study\OneDrive - Manipal Academy of Higher Education\Coding\Mini-Projects\Arihant-Ledger\virt\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Study\OneDrive - Manipal Academy of Higher Education\Coding\Mini-Projects\Arihant-Ledger\virt\Lib\site-packages\click\decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Study\OneDrive - Manipal Academy of Higher Education\Coding\Mini-Projects\Arihant-Ledger\virt\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Study\OneDrive - Manipal Academy of Higher Education\Coding\Mini-Projects\Arihant-Ledger\virt\Lib\site-packages\flask\cli.py", line 953, in run_command
    raise e from None
  File "E:\Study\OneDrive - Manipal Academy of Higher Education\Coding\Mini-Projects\Arihant-Ledger\virt\Lib\site-packages\flask\cli.py", line 937, in run_command
    app: WSGIApplication = info.load_app()
                           ^^^^^^^^^^^^^^^
  File "E:\Study\OneDrive - Manipal Academy of Higher Education\Coding\Mini-Projects\Arihant-Ledger\virt\Lib\site-packages\flask\cli.py", line 339, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Study\OneDrive - Manipal Academy of Higher Education\Coding\Mini-Projects\Arihant-Ledger\virt\Lib\site-packages\flask\cli.py", line 245, in locate_app
    __import__(module_name)
  File "E:\Study\OneDrive - Manipal Academy of Higher Education\Coding\Mini-Projects\Arihant-Ledger\app.py", line 1, in <module>       
    from ledger import app
  File "E:\Study\OneDrive - Manipal Academy of Higher Education\Coding\Mini-Projects\Arihant-Ledger\ledger\__init__.py", line 16, in <module>
    mongo = PyMongo(app)
            ^^^^^^^^^^^^
  File "E:\Study\OneDrive - Manipal Academy of Higher Education\Coding\Mini-Projects\Arihant-Ledger\virt\Lib\site-packages\flask_pymongo\__init__.py", line 110, in __init__
    self.init_app(app, uri, *args, **kwargs)
  File "E:\Study\OneDrive - Manipal Academy of Higher Education\Coding\Mini-Projects\Arihant-Ledger\virt\Lib\site-packages\flask_pymongo\__init__.py", line 147, in init_app
    parsed_uri = uri_parser.parse_uri(uri)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Study\OneDrive - Manipal Academy of Higher Education\Coding\Mini-Projects\Arihant-Ledger\virt\Lib\site-packages\pymongo\uri_parser.py", line 543, in parse_uri
    dns_options = dns_resolver.get_options()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Study\OneDrive - Manipal Academy of Higher Education\Coding\Mini-Projects\Arihant-Ledger\virt\Lib\site-packages\pymongo\srv_resolver.py", line 99, in get_options
    raise ConfigurationError(str(exc)) from None
pymongo.errors.ConfigurationError: The resolution lifetime expired after 21.158 seconds: Server Do53:192.168.1.1@53 answered The DNS operation timed out.; Server Do53:192.168.1.1@53 answered The DNS operation timed out.; Server Do53:192.168.1.1@53 answered The DNS operation timed out.; Server Do53:192.168.1.1@53 answered The DNS operation timed out.; Server Do53:192.168.1.1@53 answered The DNS operation timed out.; Server Do53:192.168.1.1@53 answered The DNS operation timed out.; Server Do53:192.168.1.1@53 answered The DNS operation timed out.

Any suggestions or changes I should be focusing on?

**Comment by blink1073** [comment]
Hi @RampageousRJ, if you're still facing this issue, I'd suggest trying the solutions mentioned here: https://stackoverflow.com/a/78928284
