### ISSUE TITLE
Hard to understand error message when there is no database in URI

### ISSUE THREAD

**Issue by kissgyorgy** [dcrosta/flask-pymongo#54]
Mongodb documentation says that [database part is optional](http://docs.mongodb.org/manual/reference/connection-string/#standard-connection-string-format):

> `/databse`
> Optional. The name of the database to authenticate if the connection string includes authentication credentials in the form of username:password@. If /database is not specified and the connection string includes credentials, the driver will authenticate to the admin database.

this library should default to that.
Also the error message is very hard to understand:

```
Traceback (most recent call last):
  File "connect_to_mongodb.py", line 12, in <module>
    mongo = PyMongo(app)
  File "/home/walkman/.virtualenvs/project/lib/python3.4/site-packages/flask_pymongo/__init__.py", line 98, in __init__
    self.init_app(app, config_prefix)
  File "/home/walkman/.virtualenvs/project/lib/python3.4/site-packages/flask_pymongo/__init__.py", line 235, in init_app
    db = cx[dbname]
  File "/home/walkman/.virtualenvs/project/lib/python3.4/site-packages/pymongo/mongo_client.py", line 1320, in __getitem__
    return self.__getattr__(name)
  File "/home/walkman/.virtualenvs/project/lib/python3.4/site-packages/flask_pymongo/wrappers.py", line 40, in __getattr__
    attr = super(MongoClient, self).__getattr__(name)
  File "/home/walkman/.virtualenvs/project/lib/python3.4/site-packages/pymongo/mongo_client.py", line 1309, in __getattr__
    return database.Database(self, name)
  File "/home/walkman/.virtualenvs/project/lib/python3.4/site-packages/pymongo/database.py", line 76, in __init__
    "of %s" % (str.__name__,))
TypeError: name must be an instance of str
```

The Exception thrown because database name will be `None` [based on parsed `MONGO_URI`](https://github.com/dcrosta/flask-pymongo/blob/master/flask_pymongo/__init__.py#L133)

**Comment by dcrosta** [comment]
Fixed in ab0fee2
